class GenreMapper:
    """Clase para mapear géneros de películas del español al inglés."""

    @staticmethod
    def get_genre_map():
        """Retorna el diccionario de mapeo de géneros español -> inglés."""
        return {
            'acción': 'Action',
            'accion': 'Action',
            'aventura': 'Adventure',
            'comedia': 'Comedy',
            'drama': 'Drama',
            'ciencia ficción': 'Sci-Fi',
            'ciencia ficcion': 'Sci-Fi',
            'terror': 'Horror',
            'miedo': 'Horror',
            'romántica': 'Romance',
            'romantica': 'Romance',
            'thriller': 'Thriller',
            'animación': 'Animation',
            'animacion': 'Animation',
            'documental': 'Documentary',
            'fantasia': 'Fantasy',
            'fantasía': 'Fantasy',
            'guerra': 'War',
            'historia': 'History',
            'musical': 'Musical',
            'misterio': 'Mystery',
            'western': 'Western',
            'samurai': 'Samurai',
            'atraco': 'Heist',
            'hombre lobo': 'Werewolf Horror',
            'baloncesto': 'Basketball',
            'deportes': 'Sport',
            'tragedia': 'Tragedy',
            'caper': 'Caper',
            'romance trágico': 'Tragic Romance',
            'comedia screwball': 'Screwball Comedy',
            'viaje': 'Road Trip',
            'ciencia y tecnología': 'Science & Technology Documentary',
            'dinosaurios': 'Dinosaur Adventure',
            'josei': 'Josei',
            'romance juvenil': 'Teen Romance',
            'comedia navideña': 'Holiday Comedy',
            'steampunk': 'Steampunk',
            'viajes': 'Travel Documentary',
            'stand-up': 'Stand-Up',
            'musical de rock': 'Rock Musical',
            'serie b': 'B-Horror',
            'slice of life': 'Slice of Life',
            'folk horror': 'Folk Horror',
            'romance erótico': 'Steamy Romance',
            'drama médico': 'Medical Drama',
            'crimen real': 'True Crime',
            'deporte extremo': 'Extreme Sport',
            'animación por computadora': 'Computer Animation',
            'comedia adulta': 'Raunchy Comedy',
            'fe y espiritualidad': 'Faith & Spirituality Documentary',
            'cambio de cuerpo': 'Body Swap Comedy',
            'comedia de amigos': 'Buddy Comedy',
            'gángster': 'Gangster',
            'giallo': 'Giallo',
            'western clásico': 'Classical Western',
            'jukebox musical': 'Jukebox Musical',
            'kung fu': 'Kung Fu',
            'drama político': 'Political Drama',
            'drama juvenil': 'Teen Drama',
            'horror psicológico': 'Psychological Horror',
            'épica histórica': 'Historical Epic',
            'superhéroe': 'Superhero',
            'motorsport': 'Motorsport',
            'thriller psicológico': 'Psychological Thriller',
            'aventura marítima': 'Sea Adventure',
            'horror zombie': 'Zombie Horror',
            'épica sci-fi': 'Sci-Fi Epic',
            'mockumentary': 'Mockumentary',
            'acción serie b': 'B-Action',
            'drama policial': 'Cop Drama',
            'sátira': 'Satire',
            'inteligencia artificial': 'Artificial Intelligence',
            'western contemporáneo': 'Contemporary Western',
            'drama de época': 'Costume Drama',
            'fútbol': 'Football',
            'aventura animal': 'Animal Adventure',
            'aventura desierto': 'Desert Adventure',
            'found footage': 'Found Footage Horror',
            'drama coreano': 'Korean Drama',
            'buddy cop': 'Buddy Cop',
            'comedia stoner': 'Stoner Comedy',
            'shonen': 'Shōnen',
            'comedia negra': 'Dark Comedy',
            'animación navideña': 'Holiday Animation',
            'romance feel-good': 'Feel-Good Romance',
            'animación stop motion': 'Stop Motion Animation',
            'aventura urbana': 'Urban Adventure',
            'sci-fi espacial': 'Space Sci-Fi',
            'horror splatter': 'Splatter Horror',
            'cyberpunk': 'Cyberpunk',
            'western épico': 'Western Epic',
            'coming-of-age': 'Coming-of-Age',
            'documental histórico': 'History Documentary',
            'horror vampiros': 'Vampire Horror',
            'horror brujas': 'Witch Horror',
            'béisbol': 'Baseball',
            'documental crimen': 'Crime Documentary',
            'musical pop': 'Pop Musical',
            'documental musical': 'Music Documentary',
            'misterio acogedor': 'Cozy Mystery',
            'concurso': 'Game Show',
            'espada y hechicería': 'Sword & Sorcery',
            'aventura jungla': 'Jungle Adventure',
            'aventura épica': 'Adventure Epic',
            'deportes acuáticos': 'Water Sport',
            'romance navideño': 'Holiday Romance',
            'música': 'Music',
            'mecha': 'Mecha',
            'seinen': 'Seinen',
            'animación adulta': 'Adult Animation',
            'crimen': 'Crime',
            'slasher': 'Slasher Horror',
            'desastre': 'Disaster',
            'documental gastronomía': 'Food Documentary',
            'farsa': 'Farce',
            'comedia juvenil': 'Teen Comedy',
            'anime': 'Anime',
            'parodia': 'Parody',
            'espionaje': 'Spy',
            'musical clásico': 'Classic Musical',
            'horror monstruos': 'Monster Horror',
            'fútbol soccer': 'Soccer',
            'comedia romántica': 'Romantic Comedy',
            'supervivencia': 'Survival',
            'drama legal': 'Legal Drama',
            'drama del espectáculo': 'Showbiz Drama',
            'wuxia': 'Wuxia',
            'épica de acción': 'Action Epic',
            'shojo': 'Shōjo',
            'fantasía sobrenatural': 'Supernatural Fantasy',
            'documental naturaleza': 'Nature Documentary',
            'búsqueda': 'Quest',
            'capa y espada': 'Swashbuckler',
            'crimen drogas': 'Drug Crime',
            'aventura montaña': 'Mountain Adventure',
            'boxeo': 'Boxing',
            'misterio suspense': 'Suspense Mystery',
            'thriller político': 'Political Thriller',
            'slapstick': 'Slapstick',
            'detective hard-boiled': 'Hard-boiled Detective',
            'fantasía juvenil': 'Teen Fantasy',
            'épica romántica': 'Romantic Epic',
            'biografía': 'Biography',
            'procedimiento policial': 'Police Procedural',
            'animación tradicional': 'Hand-Drawn Animation',
            'thriller erótico': 'Erotic Thriller',
            'kaiju': 'Kaiju',
            'fantasía oscura': 'Dark Fantasy',
            'documental político': 'Political Documentary',
            'aventura juvenil': 'Teen Adventure',
            'horror juvenil': 'Teen Horror',
            'gun fu': 'Gun Fu',
            'thriller conspiración': 'Conspiracy Thriller',
            'documental militar': 'Military Documentary',
            'noticias': 'News',
            'drama financiero': 'Financial Drama',
            'whodunnit': 'Whodunnit',
            'aventura global': 'Globetrotting Adventure',
            'espada y sandalia': 'Sword & Sandal',
            'asesino en serie': 'Serial Killer',
            'detective torpe': 'Bumbling Detective',
            'comedia de alto concepto': 'High-Concept Comedy',
            'concierto': 'Concert',
            'docudrama': 'Docudrama',
            'body horror': 'Body Horror',
            'familia': 'Family',
            'acción con coches': 'Car Action',
            'comedia excéntrica': 'Quirky Comedy',
            'drama de época': 'Period Drama',
            'épica': 'Epic',
            'viaje en el tiempo': 'Time Travel',
            'horror sobrenatural': 'Supernatural Horror',
            'sci-fi distópica': 'Dystopian Sci-Fi',
            'romance oscuro': 'Dark Romance',
            'cuento de hadas': 'Fairy Tale',
            'spaghetti western': 'Spaghetti Western',
            'drama carcelario': 'Prison Drama',
            'navidad': 'Holiday',
            'invasión alienígena': 'Alien Invasion',
            'cyber thriller': 'Cyber Thriller',
            'isekai': 'Isekai',
            'épica fantástica': 'Fantasy Epic',
            'drama psicológico': 'Psychological Drama',
            'comedia de sketches': 'Sketch Comedy',
            'thriller legal': 'Legal Thriller',
            'sitcom': 'Sitcom',
            'iyashikei': 'Iyashikei',
            'artes marciales': 'Martial Arts',
            'one-person army': 'One-Person Army Action',
            'drama laboral': 'Workplace Drama',
            'épica de guerra': 'War Epic',
            'familiar': 'Family',
            'navideño': 'Holiday Family'
        }